// <auto-generated />
using MDPMS.Database.Localization.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Migrations.Migrations
{
    [DbContext(typeof(LocalizationDatabaseContext))]
    [Migration("20180523213539_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("MDPMS.Database.Localization.Models.Key", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("KeyName");

                    b.HasKey("Id");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("MDPMS.Database.Localization.Models.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("MDPMS.Database.Localization.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("KeyId");

                    b.Property<string>("KeyLocalizationValue");

                    b.Property<int>("LocalizationId");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.HasIndex("LocalizationId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("MDPMS.Database.Localization.Models.Value", b =>
                {
                    b.HasOne("MDPMS.Database.Localization.Models.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MDPMS.Database.Localization.Models.Localization", "Localization")
                        .WithMany()
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
