// <auto-generated />
using MDPMS.EfDatabase.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Migrations.Migrations
{
    [DbContext(typeof(MDPMSDatabaseContext))]
    [Migration("20171204185035_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("MDPMS.EfDatabase.EfModels.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GenderReadable");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("MDPMS.EfDatabase.EfModels.Household", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("ExternalId");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<string>("Name");

                    b.Property<bool>("SoftDeleted");

                    b.HasKey("InternalId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("MDPMS.EfDatabase.EfModels.Person", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<bool>("DateOfBirthIsApproximate");

                    b.Property<int?>("ExternalId");

                    b.Property<string>("FirstName");

                    b.Property<int?>("GenderId");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LastUpdatedAt");

                    b.Property<string>("MiddleName");

                    b.Property<bool>("SoftDeleted");

                    b.HasKey("InternalId");

                    b.HasIndex("GenderId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MDPMS.EfDatabase.EfModels.Person", b =>
                {
                    b.HasOne("MDPMS.EfDatabase.EfModels.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");
                });
#pragma warning restore 612, 618
        }
    }
}
